version: "3"

services:

  db:
    container_name: "sopherapps.metabase.pg"
    restart: "always"
    image: alpy-pg
    build: ./pg
    env_file:
      - ./config/postgres.env
    volumes:
      - data:/var/lib/postgresql/data/
    ports:
      - 54320:5432

  metabase:
    container_name: "sopherapps.metabase.metabase"
    restart: "always"
    image: metabase/metabase
    env_file:
      - ./config/metabase_database.env
    ports:
      - 3000:3000

volumes:
  data:
